#!/usr/bin/env python3
"""Regenerate lib/lists/data/index.ts from the JSON files in public/lists.

The files live under public/ so the app can fetch a list on demand instead of
bundling a megabyte of places into every visit; this registry is for the
tests and the validator, which read them all at once."""
import os, json
root = os.path.join(os.path.dirname(__file__), "..", "..")
d = os.path.join(root, "lib", "lists", "data")
pub = os.path.join(root, "public", "lists")
files = sorted(f[:-5] for f in os.listdir(pub) if f.endswith(".json"))
lines = ['// Generated by scripts/lists/registry.py — one import per list file in public/lists.',
         '// Node-side only (tests, validator): the app fetches these files on demand.',
         'import type { WorldList } from "../schema";', '']
lines += [f'import {f} from "../../../public/lists/{f}.json";' for f in files]
lines += ['', 'export const LIST_FILES: WorldList[] = [' + ", ".join(f"{f} as unknown as WorldList" for f in files) + '];', '']
open(os.path.join(d, "index.ts"), "w").write("\n".join(lines))
print(f"registered {len(files)} lists: {', '.join(files) or '(none yet)'}")
