#!/usr/bin/env python3
"""Regenerate lib/lists/data/index.ts from the JSON files present."""
import os, json
d = os.path.join(os.path.dirname(__file__), "..", "..", "lib", "lists", "data")
files = sorted(f[:-5] for f in os.listdir(d) if f.endswith(".json"))
lines = ['// Generated by scripts/lists/registry.py — one import per list file present.',
         'import type { WorldList } from "../schema";', '']
lines += [f'import {f} from "./{f}.json";' for f in files]
lines += ['', 'export const LIST_FILES: WorldList[] = [' + ", ".join(f"{f} as unknown as WorldList" for f in files) + '];', '']
open(os.path.join(d, "index.ts"), "w").write("\n".join(lines))
print(f"registered {len(files)} lists: {', '.join(files) or '(none yet)'}")
