// Generated by scripts/lists/registry.py — one import per list file present.
import type { WorldList } from "../schema";

import beaches from "./beaches.json";
import dive from "./dive.json";
import drone from "./drone.json";
import hikes from "./hikes.json";
import kite from "./kite.json";
import nightskies from "./nightskies.json";
import restaurants from "./restaurants.json";
import roadtrips from "./roadtrips.json";
import ski from "./ski.json";
import surf from "./surf.json";

export const LIST_FILES: WorldList[] = [beaches as unknown as WorldList, dive as unknown as WorldList, drone as unknown as WorldList, hikes as unknown as WorldList, kite as unknown as WorldList, nightskies as unknown as WorldList, restaurants as unknown as WorldList, roadtrips as unknown as WorldList, ski as unknown as WorldList, surf as unknown as WorldList];
