// A curated world layer: UNESCO sites, iconic monuments, great national parks
// and cultural landmarks, each with a one-line hook. Bundled offline so the
// layer always renders; categories drive the marker icon + color.

export type LandmarkCategory = "unesco" | "monument" | "park" | "culture";

export interface Landmark {
  id: string;
  name: string;
  countryCode: string;
  lng: number;
  lat: number;
  category: LandmarkCategory;
  blurb: string;
}

export const LANDMARK_CATEGORY_META: Record<
  LandmarkCategory,
  { label: string; color: string; glyph: string }
> = {
  unesco: { label: "UNESCO World Heritage", color: "#b3862d", glyph: "🏛" },
  monument: { label: "Monument", color: "#7a5ea8", glyph: "🗽" },
  park: { label: "National park", color: "#2e8f57", glyph: "🌲" },
  culture: { label: "Cultural site", color: "#c65d3b", glyph: "🎭" },
};

// [name, cc, lng, lat, category, blurb]
type Row = [string, string, number, number, LandmarkCategory, string];

const rows: Row[] = [
  // ── Europe ────────────────────────────────────────────────────────────────
  ["Eiffel Tower", "FR", 2.2945, 48.8584, "monument", "Gustave Eiffel's 1889 iron lattice — the symbol of Paris."],
  ["Louvre Museum", "FR", 2.3376, 48.8606, "culture", "The world's most-visited museum, home to the Mona Lisa."],
  ["Mont-Saint-Michel", "FR", -1.5115, 48.6361, "unesco", "A tidal-island abbey rising straight out of the sea."],
  ["Palace of Versailles", "FR", 2.1204, 48.8049, "unesco", "The Sun King's palace of mirrors and endless gardens."],
  ["Carcassonne", "FR", 2.3637, 43.2065, "unesco", "A double-walled medieval citadel in Languedoc."],
  ["Pont du Gard", "FR", 4.5353, 43.9475, "unesco", "A three-tiered Roman aqueduct spanning the Gardon."],
  ["Chartres Cathedral", "FR", 1.4877, 48.4477, "unesco", "High Gothic perfection with 12th-century stained glass."],
  ["Colosseum", "IT", 12.4922, 41.8902, "monument", "Rome's 50,000-seat amphitheatre of gladiators."],
  ["Venice and its Lagoon", "IT", 12.3155, 45.4408, "unesco", "A city built on 118 islands, streets of water."],
  ["Leaning Tower of Pisa", "IT", 10.3966, 43.7230, "monument", "The bell tower that famously refused to stand straight."],
  ["Florence Historic Centre", "IT", 11.2558, 43.7696, "unesco", "The cradle of the Renaissance — Duomo, Uffizi, Ponte Vecchio."],
  ["Pompeii", "IT", 14.4989, 40.7462, "unesco", "A Roman city frozen in ash since 79 AD."],
  ["Amalfi Coast", "IT", 14.6027, 40.6333, "unesco", "Cliff villages stacked above the Tyrrhenian Sea."],
  ["Cinque Terre", "IT", 9.7085, 44.1237, "unesco", "Five pastel fishing villages linked by cliff paths."],
  ["Dolomites", "IT", 11.8500, 46.4102, "park", "Pale limestone towers — the Alps at their most dramatic."],
  ["Sagrada Família", "ES", 2.1744, 41.4036, "monument", "Gaudí's still-unfinished basilica, begun in 1882."],
  ["Alhambra", "ES", -3.5886, 37.1760, "unesco", "Moorish palaces and courtyards above Granada."],
  ["Park Güell", "ES", 2.1527, 41.4145, "culture", "Gaudí's mosaic wonderland overlooking Barcelona."],
  ["Santiago de Compostela", "ES", -8.5449, 42.8806, "unesco", "The end of the Camino — pilgrimage since the 9th century."],
  ["Ibiza Biodiversity", "ES", 1.4321, 38.9067, "unesco", "Posidonia meadows and fortified old town by the sea."],
  ["Belém Tower", "PT", -9.2160, 38.6916, "unesco", "Lisbon's 16th-century fortress guarding the Tagus."],
  ["Jerónimos Monastery", "PT", -9.2076, 38.6979, "unesco", "Manueline masterpiece funded by the spice trade."],
  ["Porto Historic Centre", "PT", -8.6110, 41.1407, "unesco", "Azulejo-clad riverside city of port wine cellars."],
  ["Sintra", "PT", -9.3906, 38.7977, "unesco", "Romantic palaces scattered through misty hills."],
  ["Stonehenge", "GB", -1.8262, 51.1789, "unesco", "A 5,000-year-old stone circle on Salisbury Plain."],
  ["Tower of London", "GB", -0.0759, 51.5081, "unesco", "Norman fortress, royal prison, home of the Crown Jewels."],
  ["Big Ben & Westminster", "GB", -0.1246, 51.5007, "unesco", "The Gothic-revival heart of British government."],
  ["Edinburgh Old Town", "GB", -3.1900, 55.9500, "unesco", "A medieval spine running castle to palace."],
  ["Giant's Causeway", "GB", -6.5116, 55.2408, "unesco", "40,000 interlocking basalt columns meeting the Atlantic."],
  ["Lake District", "GB", -3.0886, 54.4609, "park", "England's fells and lakes that inspired the Romantics."],
  ["Brandenburg Gate", "DE", 13.3777, 52.5163, "monument", "Berlin's neoclassical symbol of division and reunion."],
  ["Neuschwanstein Castle", "DE", 10.7498, 47.5576, "monument", "Ludwig II's fairy-tale castle in the Bavarian Alps."],
  ["Cologne Cathedral", "DE", 6.9583, 50.9413, "unesco", "Twin Gothic spires 600 years in the making."],
  ["Museum Island", "DE", 13.3978, 52.5169, "unesco", "Five world-class museums on a Spree island."],
  ["Acropolis of Athens", "GR", 23.7267, 37.9715, "unesco", "The Parthenon crowning the birthplace of democracy."],
  ["Meteora", "GR", 21.6306, 39.7217, "unesco", "Monasteries perched on sandstone pillars in the sky."],
  ["Delphi", "GR", 22.5010, 38.4824, "unesco", "The oracle's sanctuary on the slopes of Parnassus."],
  ["Santorini Caldera", "GR", 25.4319, 36.4072, "culture", "White villages rimming a drowned volcano."],
  ["Anne Frank House", "NL", 4.8840, 52.3752, "culture", "The hidden annex behind an Amsterdam canal house."],
  ["Kinderdijk Windmills", "NL", 4.6444, 51.8839, "unesco", "Nineteen 18th-century mills keeping the polder dry."],
  ["Grand-Place Brussels", "BE", 4.3525, 50.8467, "unesco", "A guildhall square of gold-trimmed Baroque facades."],
  ["Bruges Historic Centre", "BE", 3.2247, 51.2093, "unesco", "Canals and belfries in a perfectly kept medieval town."],
  ["Matterhorn / Zermatt", "CH", 7.6586, 45.9766, "park", "The Alps' most photographed pyramid of rock."],
  ["Jungfrau-Aletsch", "CH", 8.0300, 46.5000, "unesco", "The great glacier of the Bernese Alps."],
  ["Schönbrunn Palace", "AT", 16.3122, 48.1845, "unesco", "The Habsburgs' 1,441-room summer residence."],
  ["Hallstatt", "AT", 13.6493, 47.5622, "unesco", "A lakeside salt-mining village older than Rome."],
  ["Prague Historic Centre", "CZ", 14.4205, 50.0875, "unesco", "A skyline of a hundred spires over the Vltava."],
  ["Charles Bridge", "CZ", 14.4114, 50.0865, "monument", "Statue-lined Gothic bridge begun in 1357."],
  ["Auschwitz-Birkenau Memorial", "PL", 19.2033, 50.0359, "unesco", "The memorial and museum on the site of the Nazi camp."],
  ["Kraków Old Town", "PL", 19.9383, 50.0614, "unesco", "Europe's largest medieval market square."],
  ["Budapest Danube Banks", "HU", 19.0402, 47.4979, "unesco", "Parliament, castle and bridges strung along the river."],
  ["Plitvice Lakes", "HR", 15.5820, 44.8654, "park", "Sixteen terraced lakes joined by waterfalls."],
  ["Dubrovnik Old City", "HR", 18.1077, 42.6403, "unesco", "Marble streets inside mighty sea walls."],
  ["Kotor Bay", "ME", 18.7712, 42.4247, "unesco", "A fjord-like bay guarded by Venetian walls."],
  ["Mostar Old Bridge", "BA", 17.8150, 43.3372, "unesco", "The rebuilt Ottoman arch over the Neretva."],
  ["Rila Monastery", "BG", 23.3403, 42.1335, "unesco", "Bulgaria's striped-arch spiritual stronghold."],
  ["Bran Castle", "RO", 25.3672, 45.5150, "monument", "The Carpathian castle of Dracula legend."],
  ["Geirangerfjord", "NO", 7.0956, 62.1049, "unesco", "Waterfalls plunging into Norway's steepest fjord."],
  ["Lofoten Islands", "NO", 13.6090, 68.2094, "park", "Arctic peaks rising straight from fishing villages."],
  ["Gamla Stan Stockholm", "SE", 18.0700, 59.3251, "culture", "The island old town where Stockholm began."],
  ["Suomenlinna", "FI", 24.9857, 60.1454, "unesco", "A sea fortress spread across six Helsinki islands."],
  ["Thingvellir", "IS", -21.1290, 64.2559, "unesco", "The world's first parliament, in a rift between continents."],
  ["Kremlin & Red Square", "RU", 37.6208, 55.7539, "unesco", "The fortified heart of Russian power."],
  ["Hermitage Museum", "RU", 30.3146, 59.9398, "culture", "Three million works in the Winter Palace."],
  ["Hagia Sophia", "TR", 28.9802, 41.0086, "unesco", "Byzantine dome, Ottoman minarets, 1,500 years of history."],
  ["Cappadocia / Göreme", "TR", 34.8289, 38.6431, "unesco", "Fairy chimneys, cave churches and dawn balloons."],
  ["Ephesus", "TR", 27.3417, 37.9411, "unesco", "The marble streets of a great Roman port city."],
  ["Pamukkale", "TR", 29.1190, 37.9203, "unesco", "White travertine terraces of thermal water."],

  // ── Europe (more) ─────────────────────────────────────────────────────────
  ["Notre-Dame de Paris", "FR", 2.3499, 48.853, "monument", "The Gothic heart of France, risen from the 2019 fire."],
  ["Arc de Triomphe", "FR", 2.295, 48.8738, "monument", "Napoleon's arch at the hub of twelve avenues."],
  ["Sacré-Cœur", "FR", 2.3431, 48.8867, "culture", "The white basilica crowning Montmartre's artists' hill."],
  ["Château de Chambord", "FR", 1.517, 47.616, "monument", "The Loire's most extravagant château, 440 rooms."],
  ["Dune du Pilat", "FR", -1.21, 44.59, "park", "Europe's tallest sand dune, pine forest on one side, Atlantic the other."],
  ["Verdon Gorge", "FR", 6.33, 43.75, "park", "Turquoise water through Europe's grandest canyon."],
  ["Étretat Cliffs", "FR", 0.20, 49.71, "park", "The chalk arches Monet painted, over and over."],
  ["Strasbourg Grande Île", "FR", 7.75, 48.58, "unesco", "Half-timbered Alsace around a rose sandstone cathedral."],
  ["Vieux Lyon", "FR", 4.83, 45.76, "unesco", "Renaissance traboules and the best food city in France."],
  ["Palais des Papes", "FR", 4.807, 43.951, "unesco", "The popes' 14th-century fortress in Avignon."],
  ["Rocamadour", "FR", 1.62, 44.80, "culture", "A pilgrimage village stacked up a cliff face."],
  ["Calanques de Piana", "FR", 8.63, 42.25, "unesco", "Corsica's red granite spires above the Gulf of Porto."],
  ["Seville Cathedral & Alcázar", "ES", -5.993, 37.386, "unesco", "The world's largest Gothic cathedral beside a Moorish palace."],
  ["Toledo", "ES", -4.02, 39.86, "unesco", "The city of three cultures on a bend of the Tagus."],
  ["Segovia Aqueduct", "ES", -4.118, 40.948, "unesco", "167 Roman arches without a drop of mortar."],
  ["Mezquita de Córdoba", "ES", -4.78, 37.879, "unesco", "A forest of candy-striped arches, mosque and cathedral at once."],
  ["Salamanca", "ES", -5.66, 40.96, "unesco", "Golden sandstone university city, teaching since 1218."],
  ["Picos de Europa", "ES", -4.85, 43.19, "park", "Limestone peaks rising straight from the Atlantic coast."],
  ["Mount Teide", "ES", -16.64, 28.27, "unesco", "Spain's highest peak, a volcano above Tenerife's clouds."],
  ["Timanfaya", "ES", -13.79, 29.01, "park", "Lanzarote's Martian fire mountains."],
  ["Ordesa Valley", "ES", 0.03, 42.65, "park", "The Pyrenees' answer to Yosemite."],
  ["Montserrat", "ES", 1.83, 41.60, "culture", "Serrated mountain monastery guarding the Black Madonna."],
  ["Ronda", "ES", -5.166, 36.74, "culture", "A town split by a 120-m gorge and stitched by a stone bridge."],
  ["Douro Valley", "PT", -7.80, 41.16, "unesco", "The world's oldest demarcated wine region, terraced to the river."],
  ["Laurisilva of Madeira", "PT", -17.00, 32.73, "unesco", "A prehistoric laurel forest in permanent mist."],
  ["Pico Island", "PT", -28.40, 38.47, "unesco", "An Azorean volcano ringed by black-stone vineyards."],
  ["Óbidos", "PT", -9.16, 39.36, "culture", "A whitewashed medieval town inside complete walls."],
  ["Benagil Cave", "PT", -8.42, 37.09, "park", "The Algarve's domed sea cave with its own beach."],
  ["Bath", "GB", -2.36, 51.38, "unesco", "Roman baths and Georgian crescents in honeyed stone."],
  ["Canterbury Cathedral", "GB", 1.083, 51.28, "unesco", "England's mother church and Becket's shrine."],
  ["Hadrian's Wall", "GB", -2.50, 55.00, "unesco", "Rome's northern frontier, coast to coast."],
  ["Snowdonia / Eryri", "GB", -3.90, 53.07, "park", "Wales' highest peaks and slate-hewn valleys."],
  ["Ben Nevis & Glen Coe", "GB", -5.00, 56.80, "park", "Britain's rooftop and its most brooding glen."],
  ["Isle of Skye", "GB", -6.20, 57.40, "park", "The Quiraing, fairy pools and Cuillin ridges."],
  ["Buckingham Palace", "GB", -0.1419, 51.5014, "monument", "The monarchy's London front door."],
  ["Windsor Castle", "GB", -0.604, 51.484, "monument", "The oldest occupied castle in the world."],
  ["York Minster", "GB", -1.082, 53.962, "culture", "Northern Europe's largest Gothic cathedral, in a Viking city."],
  ["Oxford", "GB", -1.256, 51.752, "culture", "Dreaming spires and 900 years of scholarship."],
  ["Durdle Door", "GB", -2.277, 50.62, "park", "The Jurassic Coast's limestone arch."],
  ["Cliffs of Moher", "IE", -9.43, 52.97, "park", "700-ft Atlantic cliffs alive with puffins."],
  ["Newgrange", "IE", -6.475, 53.695, "unesco", "A passage tomb older than the pyramids, lit each solstice."],
  ["Ring of Kerry", "IE", -9.90, 51.95, "park", "Ireland's classic 179-km coastal circuit."],
  ["Trinity College & Book of Kells", "IE", -6.257, 53.344, "culture", "The Long Room library and a 1,200-year-old gospel."],
  ["Rothenburg ob der Tauber", "DE", 10.18, 49.38, "culture", "Germany's fairy-tale walled town on the Romantic Road."],
  ["East Side Gallery", "DE", 13.44, 52.505, "culture", "The Berlin Wall's longest surviving stretch, now a mural mile."],
  ["Zugspitze", "DE", 10.98, 47.42, "park", "Germany's highest peak, glacier and golden cross on top."],
  ["Black Forest", "DE", 8.20, 48.00, "park", "Cuckoo clocks, cake, and deep spruce valleys."],
  ["Bamberg", "DE", 10.89, 49.89, "unesco", "A perfectly preserved island town of smoked beer."],
  ["Aachen Cathedral", "DE", 6.084, 50.775, "unesco", "Charlemagne's octagon — Germany's first World Heritage site."],
  ["Heidelberg Castle", "DE", 8.715, 49.41, "monument", "Romantic ruins above the Neckar and Germany's oldest university."],
  ["Bastei Bridge", "DE", 14.07, 50.96, "park", "Sandstone towers of Saxon Switzerland linked by a stone bridge."],
  ["St. Peter's Basilica", "VA", 12.4534, 41.9022, "unesco", "Michelangelo's dome over Christendom's greatest church."],
  ["Trevi Fountain", "IT", 12.483, 41.901, "monument", "Toss a coin to return to Rome."],
  ["Pantheon", "IT", 12.477, 41.899, "monument", "Rome's 2,000-year-old dome, still the world's largest unreinforced."],
  ["Milan Duomo", "IT", 9.191, 45.464, "monument", "Six centuries of marble spires — walk on the roof."],
  ["Lake Como", "IT", 9.26, 46.00, "park", "Alpine water framed by villas and cypress."],
  ["Sassi di Matera", "IT", 16.61, 40.666, "unesco", "Cave dwellings inhabited for 9,000 years."],
  ["Alberobello", "IT", 17.24, 40.78, "unesco", "Puglia's hobbit-like trulli cones."],
  ["Siena", "IT", 11.33, 43.32, "unesco", "The Palio's shell-shaped piazza and striped duomo."],
  ["San Gimignano", "IT", 11.04, 43.47, "unesco", "Medieval Manhattan — fourteen surviving tower houses."],
  ["Val d'Orcia", "IT", 11.62, 43.02, "unesco", "The cypress-lined Tuscany of every postcard."],
  ["Mount Etna", "IT", 14.995, 37.75, "unesco", "Europe's tallest and busiest volcano."],
  ["Valley of the Temples", "IT", 13.585, 37.29, "unesco", "Greek temples better preserved than Greece's own."],
  ["Herculaneum", "IT", 14.348, 40.806, "unesco", "Pompeii's richer, better-preserved neighbor."],
  ["Portofino", "IT", 9.21, 44.303, "culture", "The Riviera's tiny, glamorous harbor."],
  ["Nyhavn", "DK", 12.591, 55.680, "culture", "Copenhagen's gabled canal of Hans Christian Andersen."],
  ["Kronborg Castle", "DK", 12.62, 56.04, "unesco", "Hamlet's Elsinore guarding the Øresund."],
  ["Preikestolen", "NO", 6.19, 58.986, "park", "The Pulpit Rock's sheer 604-m drop to Lysefjord."],
  ["Trolltunga", "NO", 6.74, 60.124, "park", "The troll's tongue jutting over a 700-m void."],
  ["Bryggen", "NO", 5.323, 60.397, "unesco", "Bergen's leaning Hanseatic wharf houses."],
  ["Visby", "SE", 18.29, 57.64, "unesco", "A walled Hanseatic rose-town on Gotland."],
  ["Vasa Museum", "SE", 18.091, 59.328, "culture", "A 1628 warship raised whole from Stockholm harbor."],
  ["Abisko", "SE", 18.83, 68.35, "park", "Sweden's aurora window above the Arctic Circle."],
  ["Blue Lagoon", "IS", -22.45, 63.88, "park", "Milky geothermal water in a black lava field."],
  ["Gullfoss", "IS", -20.12, 64.327, "park", "The Golden Circle's two-tier glacial cascade."],
  ["Jökulsárlón", "IS", -16.18, 64.05, "park", "Icebergs drifting from glacier to black beach."],
  ["Lauterbrunnen", "CH", 7.909, 46.593, "park", "72 waterfalls in one impossibly steep valley."],
  ["Chapel Bridge", "CH", 8.307, 47.052, "monument", "Lucerne's painted 14th-century wooden bridge."],
  ["Bern Old Town", "CH", 7.451, 46.948, "unesco", "Six kilometres of arcades around the Zytglogge."],
  ["Grossglockner", "AT", 12.694, 47.074, "park", "Austria's highest peak and its greatest alpine road."],
  ["Salzburg Old Town", "AT", 13.045, 47.80, "unesco", "Mozart's baroque stage-set beneath a clifftop fortress."],
  ["Vienna Historic Centre", "AT", 16.37, 48.208, "unesco", "Imperial ring roads, coffeehouses and opera."],
  ["Wieliczka Salt Mine", "PL", 20.055, 49.983, "unesco", "Chapels carved 300 m down in rock salt."],
  ["Malbork Castle", "PL", 19.028, 54.04, "unesco", "The largest castle on Earth by land area, in brick."],
  ["Tatra Mountains", "PL", 19.95, 49.25, "park", "Poland's granite high country above Zakopane."],
  ["Český Krumlov", "CZ", 14.315, 48.81, "unesco", "A Bohemian storybook looped by the Vltava."],
  ["Lake Bled", "SI", 14.10, 46.36, "park", "An island church, a clifftop castle, Julian Alps behind."],
  ["Postojna Cave", "SI", 14.20, 45.78, "park", "24 km of karst caverns with an underground train."],
  ["Diocletian's Palace", "HR", 16.44, 43.508, "unesco", "Split's living Roman palace — a city inside an emperor's retirement home."],
  ["Krka Waterfalls", "HR", 15.97, 43.87, "park", "Travertine cascades you can walk among."],
  ["Ohrid", "MK", 20.795, 41.117, "unesco", "A lake older than a million years, ringed by 365 churches."],
  ["Mount Olympus", "GR", 22.35, 40.09, "park", "The gods' 2,918-m throne."],
  ["Rhodes Old Town", "GR", 28.227, 36.445, "unesco", "The Knights' walled medieval city."],
  ["Knossos", "GR", 25.163, 35.298, "unesco", "The Minoan labyrinth of the bull-leapers."],
  ["Corfu Old Town", "GR", 19.92, 39.62, "unesco", "Venetian fortresses over Ionian blue."],
  ["Sighișoara", "RO", 24.79, 46.22, "unesco", "Dracula's birthplace inside a living citadel."],
  ["Transfăgărășan", "RO", 24.617, 45.60, "park", "The Carpathians' most spectacular road."],
  ["Kyiv Pechersk Lavra", "UA", 30.557, 50.435, "unesco", "Gold domes above thousand-year-old cave monasteries."],
  ["Lviv Old Town", "UA", 24.03, 49.84, "unesco", "Habsburg coffeehouse elegance in western Ukraine."],
  ["Tallinn Old Town", "EE", 24.745, 59.437, "unesco", "Europe's best-preserved medieval merchant city."],
  ["Riga Old Town", "LV", 24.105, 56.949, "unesco", "Art Nouveau capital of the Baltics."],
  ["Vilnius Old Town", "LT", 25.29, 54.68, "unesco", "A baroque maze with a bohemian republic inside."],
  ["Trakai Castle", "LT", 24.93, 54.65, "monument", "A red-brick island castle on Lake Galvė."],
  ["Lake Baikal", "RU", 108.00, 53.50, "unesco", "The world's oldest, deepest lake — a fifth of all fresh water."],
  ["Peterhof", "RU", 29.91, 59.885, "monument", "Russia's Versailles of gravity-fed fountains."],
  ["Blue Mosque", "TR", 28.9768, 41.0054, "monument", "Six minarets and 20,000 İznik tiles."],
  ["Mount Nemrut", "TR", 38.741, 37.981, "unesco", "Giant stone heads on a 2,000-year-old summit tomb."],
  ["Ölüdeniz", "TR", 29.116, 36.55, "park", "The blue lagoon under paraglider-filled skies."],
  ["Ani", "TR", 43.573, 40.507, "unesco", "The ghost city of 1,001 churches on the Armenian border."],

  // ── Asia ──────────────────────────────────────────────────────────────────
  ["Great Wall at Mutianyu", "CN", 116.5704, 40.4319, "unesco", "The wall snaking over forested ridges near Beijing."],
  ["Forbidden City", "CN", 116.3972, 39.9169, "unesco", "980 buildings of the Ming and Qing imperial court."],
  ["Terracotta Army", "CN", 109.2785, 34.3841, "unesco", "8,000 clay soldiers guarding the First Emperor."],
  ["Zhangjiajie", "CN", 110.4419, 29.3252, "park", "Quartzite pillar forests that inspired Avatar."],
  ["Li River / Guilin", "CN", 110.4269, 24.7867, "park", "Karst peaks mirrored in slow green water."],
  ["Potala Palace", "CN", 91.1175, 29.6558, "unesco", "The Dalai Lamas' thousand-room palace at 3,700 m."],
  ["Mount Fuji", "JP", 138.7274, 35.3606, "unesco", "Japan's sacred, perfectly symmetrical volcano."],
  ["Fushimi Inari Shrine", "JP", 135.7727, 34.9671, "culture", "Ten thousand vermilion torii climbing a Kyoto hill."],
  ["Kinkaku-ji", "JP", 135.7292, 35.0394, "unesco", "Kyoto's gold-leafed Zen pavilion on a mirror pond."],
  ["Itsukushima Shrine", "JP", 132.3198, 34.2960, "unesco", "The floating torii gate of Miyajima."],
  ["Himeji Castle", "JP", 134.6939, 34.8394, "unesco", "The White Heron — Japan's finest surviving castle."],
  ["Gyeongbokgung Palace", "KR", 126.9770, 37.5796, "culture", "Seoul's grand Joseon-dynasty palace."],
  ["Taj Mahal", "IN", 78.0421, 27.1751, "unesco", "Shah Jahan's white-marble monument to love."],
  ["Amber Fort", "IN", 75.8513, 26.9855, "unesco", "Rajput ramparts and mirrored halls above Jaipur."],
  ["Varanasi Ghats", "IN", 83.0107, 25.3109, "culture", "Ancient stone steps down to the sacred Ganges."],
  ["Kaziranga", "IN", 93.3712, 26.5775, "park", "Two-thirds of the world's one-horned rhinos."],
  ["Sigiriya", "LK", 80.7603, 7.9570, "unesco", "A palace ruin atop a 200 m column of rock."],
  ["Angkor Wat", "KH", 103.8670, 13.4125, "unesco", "The largest religious monument ever built."],
  ["Bagan", "MM", 94.8585, 21.1717, "unesco", "Two thousand temples scattered across a plain."],
  ["Ha Long Bay", "VN", 107.0448, 20.9101, "unesco", "1,600 limestone islands in emerald water."],
  ["Hoi An Ancient Town", "VN", 108.3380, 15.8801, "unesco", "Lantern-lit trading port frozen in the 1700s."],
  ["Luang Prabang", "LA", 102.1353, 19.8867, "unesco", "Gilded temples where the Mekong meets the Khan."],
  ["Grand Palace Bangkok", "TH", 100.4913, 13.7500, "culture", "Thailand's glittering royal temple complex."],
  ["Ayutthaya", "TH", 100.5684, 14.3559, "unesco", "Prangs and Buddhas of a fallen Siamese capital."],
  ["Borobudur", "ID", 110.2038, -7.6079, "unesco", "The world's largest Buddhist temple, ringed by volcanoes."],
  ["Komodo National Park", "ID", 119.4890, -8.5432, "park", "Home of the dragons, plus pink-sand reefs."],
  ["Bali Rice Terraces", "ID", 115.2792, -8.4312, "unesco", "The subak irrigation landscape of Jatiluwih."],
  ["Petra", "JO", 35.4444, 30.3285, "unesco", "The rose-red city carved into desert cliffs."],
  ["Wadi Rum", "JO", 35.4206, 29.5766, "park", "Lawrence of Arabia's valley of sandstone and sand."],
  ["Jerusalem Old City", "IL", 35.2345, 31.7767, "unesco", "One square kilometre sacred to three faiths."],
  ["Burj Khalifa", "AE", 55.2744, 25.1972, "monument", "The world's tallest building at 828 metres."],
  ["Sheikh Zayed Mosque", "AE", 54.4750, 24.4128, "monument", "82 white domes and the world's largest carpet."],
  ["Registan Samarkand", "UZ", 66.9758, 39.6547, "unesco", "Three tiled madrasahs on the Silk Road's grandest square."],
  ["Persepolis", "IR", 52.8916, 29.9355, "unesco", "Ceremonial capital of the Persian Empire."],

  // ── Asia (more) ───────────────────────────────────────────────────────────
  ["Sensō-ji", "JP", 139.7967, 35.7148, "culture", "Tokyo's oldest temple behind the Thunder Gate lantern."],
  ["Shibuya Crossing", "JP", 139.7005, 35.6595, "culture", "3,000 people per green light — the world's busiest scramble."],
  ["Tōdai-ji", "JP", 135.8398, 34.689, "unesco", "A 15-m bronze Buddha in one of the world's largest wooden halls."],
  ["Osaka Castle", "JP", 135.526, 34.687, "monument", "The gold-trimmed keep that unified Japan."],
  ["Hiroshima Peace Memorial", "JP", 132.4536, 34.3955, "unesco", "The A-Bomb Dome, preserved as it stood on August 6, 1945."],
  ["Nikkō", "JP", 139.60, 36.758, "unesco", "The shoguns' lavish mountain mausoleum."],
  ["Shirakawa-gō", "JP", 136.906, 36.258, "unesco", "Steep thatched farmhouses built for heavy snow."],
  ["Yakushima", "JP", 130.50, 30.34, "unesco", "Moss forests of 1,000-year-old cedars — Mononoke's island."],
  ["Daisetsuzan", "JP", 142.85, 43.66, "park", "Hokkaido's roof: brown bears and the earliest autumn colors."],
  ["Shuri Castle", "JP", 127.719, 26.217, "unesco", "The Ryukyu kings' vermilion palace in Okinawa."],
  ["The Bund", "CN", 121.49, 31.24, "culture", "Colonial riverfront facing Pudong's neon skyline."],
  ["Summer Palace", "CN", 116.275, 39.999, "unesco", "The imperial lake garden of the Qing."],
  ["Temple of Heaven", "CN", 116.407, 39.882, "unesco", "Where emperors prayed for harvests beneath a triple blue roof."],
  ["Leshan Giant Buddha", "CN", 103.77, 29.545, "unesco", "A 71-m Buddha carved into a river cliff."],
  ["Jiuzhaigou", "CN", 103.92, 33.26, "unesco", "Multicolored alpine lakes in Tibetan Sichuan."],
  ["Huangshan", "CN", 118.17, 30.13, "unesco", "The Yellow Mountains of ink-painting pines and cloud seas."],
  ["West Lake", "CN", 120.14, 30.24, "unesco", "Hangzhou's poem of causeways, pagodas and mist."],
  ["Chengdu Panda Base", "CN", 104.15, 30.73, "park", "Giant pandas doing very little, adorably."],
  ["Victoria Peak", "HK", 114.15, 22.27, "culture", "Hong Kong's skyline from 552 m — best at dusk."],
  ["Ruins of St. Paul's", "MO", 113.541, 22.198, "unesco", "Macau's iconic surviving cathedral facade."],
  ["Jeju Island", "KR", 126.53, 33.37, "unesco", "Lava tubes, haenyeo divers and Hallasan's crater."],
  ["Bulguksa", "KR", 129.33, 35.79, "unesco", "Silla Buddhism's masterpiece in Gyeongju."],
  ["Changdeokgung", "KR", 126.991, 37.579, "unesco", "The most loved of Seoul's five palaces, with a secret garden."],
  ["Gamcheon Culture Village", "KR", 129.01, 35.097, "culture", "Busan's rainbow hillside of stairs and murals."],
  ["Taroko Gorge", "TW", 121.62, 24.16, "park", "Marble cliffs 1,000 m over a jade river."],
  ["Taipei 101", "TW", 121.565, 25.034, "monument", "The bamboo-shaped tower that was once the world's tallest."],
  ["Sun Moon Lake", "TW", 120.92, 23.86, "park", "Taiwan's sacred lake ringed by temples and bike paths."],
  ["Golden Temple", "IN", 74.877, 31.62, "culture", "Sikhism's holiest shrine afloat in the Pool of Nectar."],
  ["Hawa Mahal", "IN", 75.827, 26.924, "monument", "Jaipur's pink honeycomb Palace of Winds."],
  ["Red Fort", "IN", 77.241, 28.656, "unesco", "The Mughal seat where India's independence is proclaimed each year."],
  ["Qutub Minar", "IN", 77.185, 28.524, "unesco", "A 73-m victory tower of carved red sandstone."],
  ["Gateway of India", "IN", 72.835, 18.922, "monument", "Mumbai's harborfront arch of empire and departure."],
  ["Hampi", "IN", 76.46, 15.335, "unesco", "A ruined imperial city strewn among giant boulders."],
  ["Khajuraho", "IN", 79.92, 24.85, "unesco", "Temples wrapped in the most famous carvings in India."],
  ["Ellora Caves", "IN", 75.18, 20.02, "unesco", "Kailasa temple — a mountain carved into a building."],
  ["Ajanta Caves", "IN", 75.70, 20.55, "unesco", "Buddhist cave murals two millennia old."],
  ["Kerala Backwaters", "IN", 76.35, 9.50, "park", "Houseboats drifting palm-lined lagoons."],
  ["Ranthambore", "IN", 76.50, 26.02, "park", "Tigers among ruined forts."],
  ["Mehrangarh Fort", "IN", 73.018, 26.298, "monument", "Jodhpur's blue city from 400-ft ramparts."],
  ["Udaipur City Palace", "IN", 73.68, 24.576, "monument", "The lake palaces of Rajasthan's Venice."],
  ["Everest Base Camp", "NP", 86.85, 28.00, "park", "The world's most famous trek to 5,364 m."],
  ["Kathmandu Durbar Square", "NP", 85.30, 27.70, "unesco", "Pagodas and living goddesses in the old royal plaza."],
  ["Annapurna / Pokhara", "NP", 83.82, 28.40, "park", "Lakeside gateway to the great Annapurna circuit."],
  ["Chitwan", "NP", 84.42, 27.53, "unesco", "Rhinos and gharials in Nepal's steamy lowlands."],
  ["Tiger's Nest", "BT", 89.363, 27.492, "culture", "Paro Taktsang clinging to a 900-m cliff."],
  ["Temple of the Tooth", "LK", 80.641, 7.294, "unesco", "Kandy's shrine of the Buddha's relic."],
  ["Galle Fort", "LK", 80.217, 6.026, "unesco", "A Dutch colonial sea fort turned boutique quarter."],
  ["Nine Arches Bridge", "LK", 81.06, 6.877, "culture", "Ella's viaduct through tea country, trains and all."],
  ["Yala", "LK", 81.47, 6.37, "park", "The world's densest leopard population."],
  ["Petronas Towers", "MY", 101.712, 3.158, "monument", "The twin icons of Kuala Lumpur, linked by a skybridge."],
  ["Batu Caves", "MY", 101.684, 3.237, "culture", "272 rainbow steps to a Hindu cave shrine."],
  ["George Town", "MY", 100.34, 5.415, "unesco", "Penang's street-art and street-food capital."],
  ["Mount Kinabalu", "MY", 116.56, 6.075, "unesco", "Borneo's 4,095-m granite dome above cloud forest."],
  ["Gardens by the Bay", "SG", 103.864, 1.282, "culture", "Supertrees and the world's largest glass greenhouse."],
  ["Marina Bay Sands", "SG", 103.861, 1.284, "monument", "Three towers carrying a ship-shaped skypark."],
  ["Doi Suthep", "TH", 98.92, 18.805, "culture", "Chiang Mai's golden mountain temple."],
  ["Railay", "TH", 98.84, 8.01, "park", "Limestone karst climbing paradise reachable only by boat."],
  ["Khao Sok", "TH", 98.53, 8.92, "park", "An emerald lake in one of Earth's oldest rainforests."],
  ["Sukhothai", "TH", 99.79, 17.02, "unesco", "Thailand's serene first capital."],
  ["White Temple", "TH", 99.763, 19.824, "culture", "Wat Rong Khun's surreal all-white mirror mosaic."],
  ["Kuang Si Falls", "LA", 102.11, 19.75, "park", "Turquoise travertine pools near Luang Prabang."],
  ["Phong Nha-Kẻ Bàng", "VN", 106.28, 17.59, "unesco", "Home of Sơn Đoòng, the largest cave passage on Earth."],
  ["Sa Pa Rice Terraces", "VN", 103.84, 22.34, "culture", "Hmong villages stitched into mountain steps."],
  ["Huế Imperial City", "VN", 107.577, 16.47, "unesco", "The Nguyễn emperors' walled Forbidden City."],
  ["Mỹ Sơn", "VN", 108.12, 15.76, "unesco", "Cham tower temples in a jungle valley."],
  ["Mount Bromo", "ID", 112.95, -7.94, "park", "Sunrise over a smoking crater in a sea of sand."],
  ["Raja Ampat", "ID", 130.50, -0.55, "park", "The global epicenter of marine biodiversity."],
  ["Prambanan", "ID", 110.49, -7.752, "unesco", "Java's soaring Hindu temple spires."],
  ["Nusa Penida", "ID", 115.47, -8.75, "park", "Kelingking's T-rex cliff and manta bays."],
  ["El Nido", "PH", 119.39, 11.18, "park", "Palawan's lagoons between karst towers."],
  ["Chocolate Hills", "PH", 124.17, 9.83, "park", "1,268 identical grassy mounds that brown each dry season."],
  ["Banaue Rice Terraces", "PH", 121.06, 16.93, "unesco", "2,000-year-old terraces called the eighth wonder."],
  ["Royal Palace Phnom Penh", "KH", 104.93, 11.564, "monument", "The Khmer kings' gilded riverside compound."],
  ["Shwedagon Pagoda", "MM", 96.15, 16.798, "monument", "A 99-m gold stupa said to hold the Buddha's hairs."],
  ["Inle Lake", "MM", 96.91, 20.55, "culture", "Leg-rowing fishermen and floating gardens."],

  // ── Middle East & Central Asia ────────────────────────────────────────────
  ["Dead Sea", "JO", 35.50, 31.50, "park", "Float effortlessly at the lowest point on land."],
  ["Jerash", "JO", 35.891, 32.28, "unesco", "The best-preserved Roman provincial city outside Italy."],
  ["Masada", "IL", 35.354, 31.312, "unesco", "Herod's mountaintop fortress above the Dead Sea."],
  ["Hegra / AlUla", "SA", 37.95, 26.79, "unesco", "Nabataean tombs — Petra's sister city in Arabia."],
  ["Museum of Islamic Art", "QA", 51.539, 25.295, "culture", "I.M. Pei's geometric masterpiece on Doha's corniche."],
  ["Palm Jumeirah", "AE", 55.117, 25.112, "monument", "Dubai's palm-shaped artificial island."],
  ["Louvre Abu Dhabi", "AE", 54.398, 24.534, "culture", "A rain of light beneath Jean Nouvel's dome."],
  ["Sultan Qaboos Grand Mosque", "OM", 58.39, 23.58, "monument", "Muscat's serene marble prayer halls."],
  ["Socotra", "YE", 53.80, 12.50, "unesco", "Dragon's blood trees on an alien island."],
  ["Baku Old City", "AZ", 49.837, 40.366, "unesco", "The Maiden Tower inside medieval walls, flame towers behind."],
  ["Tbilisi Old Town", "GE", 44.808, 41.688, "culture", "Sulfur baths and balconied lanes below Narikala."],
  ["Gergeti Trinity Church", "GE", 44.62, 42.66, "park", "A lone church against 5,000-m Kazbek."],
  ["Khor Virap", "AM", 44.576, 39.878, "culture", "The monastery with Ararat filling the sky."],
  ["Garni Temple", "AM", 44.73, 40.112, "monument", "The Caucasus' only standing Greco-Roman temple."],
  ["Bukhara", "UZ", 64.42, 39.775, "unesco", "A whole Silk Road city, minaret to madrasah."],
  ["Khiva", "UZ", 60.36, 41.378, "unesco", "Itchan Kala's mud walls hiding a turquoise-tiled town."],
  ["Charyn Canyon", "KZ", 79.08, 43.35, "park", "Kazakhstan's Valley of Castles."],
  ["Song-Köl", "KG", 75.13, 41.83, "park", "Yurts and horse herds around a 3,000-m steppe lake."],
  ["Band-e Amir", "AF", 67.23, 34.84, "park", "Six sapphire lakes dammed by natural travertine."],
  ["Naqsh-e Jahan Square", "IR", 51.677, 32.657, "unesco", "Isfahan's half-the-world square of blue-tiled mosques."],
  ["Nasir al-Mulk Mosque", "IR", 52.548, 29.608, "culture", "Shiraz's pink mosque lit through stained glass."],
  ["Baalbek", "LB", 36.204, 34.007, "unesco", "Rome's most colossal temples, in the Bekaa Valley."],
  ["Byblos", "LB", 35.646, 34.12, "unesco", "7,000 years of continuous habitation by the sea."],

  // ── Africa ────────────────────────────────────────────────────────────────
  ["Pyramids of Giza", "EG", 31.1342, 29.9792, "unesco", "The last standing Wonder of the Ancient World."],
  ["Luxor & Karnak", "EG", 32.6396, 25.7188, "unesco", "The greatest temple complex of ancient Egypt."],
  ["Abu Simbel", "EG", 31.6258, 22.3372, "unesco", "Ramses II's rock temples, moved stone by stone."],
  ["Marrakesh Medina", "MA", -7.9892, 31.6295, "unesco", "Souks and storytellers around Jemaa el-Fnaa."],
  ["Aït Benhaddou", "MA", -7.1318, 31.0472, "unesco", "A mudbrick ksar on the old caravan route."],
  ["Fes el-Bali", "MA", -4.9784, 34.0650, "unesco", "The world's largest living medieval medina."],
  ["Serengeti", "TZ", 34.8333, -2.3333, "park", "Two million wildebeest on the great migration."],
  ["Mount Kilimanjaro", "TZ", 37.3556, -3.0674, "park", "Africa's roof: 5,895 m from savanna to glacier."],
  ["Ngorongoro Crater", "TZ", 35.5876, -3.1614, "unesco", "A collapsed volcano teeming with big game."],
  ["Zanzibar Stone Town", "TZ", 39.1899, -6.1622, "unesco", "Swahili, Arab and Indian threads in coral-stone lanes."],
  ["Maasai Mara", "KE", 35.1439, -1.4931, "park", "Kenya's classic big-cat savanna."],
  ["Victoria Falls", "ZW", 25.8572, -17.9243, "unesco", "The smoke that thunders — 1.7 km of falling water."],
  ["Okavango Delta", "BW", 22.8996, -19.2833, "unesco", "A desert delta that floods into Eden each winter."],
  ["Etosha", "NA", 16.3288, -18.8556, "park", "Waterhole wildlife around a vast salt pan."],
  ["Sossusvlei Dunes", "NA", 15.2915, -24.7275, "park", "Apricot dunes 300 metres tall at dawn."],
  ["Table Mountain", "ZA", 18.4098, -33.9628, "park", "Cape Town's flat-topped icon with its own flora kingdom."],
  ["Kruger National Park", "ZA", 31.4847, -23.9884, "park", "South Africa's flagship Big Five reserve."],
  ["Robben Island", "ZA", 18.3712, -33.8076, "unesco", "The prison island where Mandela spent 18 years."],
  ["Lalibela", "ET", 39.0417, 12.0316, "unesco", "Eleven churches hewn straight down into rock."],
  ["Djenné Great Mosque", "ML", -4.5556, 13.9053, "unesco", "The largest mud-brick building on Earth."],

  // ── Africa (more) ─────────────────────────────────────────────────────────
  ["Cape of Good Hope", "ZA", 18.47, -34.36, "park", "The storied cape where two currents collide."],
  ["Boulders Beach", "ZA", 18.45, -34.20, "park", "African penguins waddling between granite boulders."],
  ["Blyde River Canyon", "ZA", 30.83, -24.60, "park", "The green canyon of the Three Rondavels."],
  ["Drakensberg", "ZA", 29.40, -29.00, "unesco", "The Dragon Mountains' basalt wall and San rock art."],
  ["Addo Elephant Park", "ZA", 25.75, -33.48, "park", "600 elephants in malaria-free Eastern Cape."],
  ["Fish River Canyon", "NA", 17.60, -27.50, "park", "Africa's largest canyon, 160 km of silence."],
  ["Deadvlei", "NA", 15.29, -24.76, "park", "900-year-old dead camelthorns on white clay under red dunes."],
  ["Skeleton Coast", "NA", 12.70, -19.50, "park", "Shipwrecks and seal colonies in the fog."],
  ["Chobe", "BW", 24.50, -18.50, "park", "120,000 elephants along one river."],
  ["South Luangwa", "ZM", 31.90, -13.10, "park", "The birthplace of the walking safari."],
  ["Mana Pools", "ZW", 29.40, -15.80, "unesco", "Canoe safaris past drinking elephants on the Zambezi."],
  ["Bwindi Impenetrable Forest", "UG", 29.62, -1.05, "unesco", "Half the world's mountain gorillas."],
  ["Murchison Falls", "UG", 31.68, 2.28, "park", "The Nile forced through a seven-metre gap."],
  ["Volcanoes National Park", "RW", 29.49, -1.47, "park", "Gorilla trekking in the Virunga mists."],
  ["Amboseli", "KE", 37.26, -2.65, "park", "Elephants beneath Kilimanjaro's snows."],
  ["Lake Nakuru", "KE", 36.08, -0.37, "park", "Flamingo-pink shores and guarded rhinos."],
  ["Lamu Old Town", "KE", 40.902, -2.271, "unesco", "Swahili donkey-lane island culture, 700 years old."],
  ["Mount Kenya", "KE", 37.31, -0.15, "unesco", "Africa's second peak, equatorial glaciers and all."],
  ["Simien Mountains", "ET", 38.04, 13.19, "unesco", "Gelada baboons on the roof of Africa."],
  ["Danakil Depression", "ET", 40.30, 14.24, "park", "Neon sulfur springs in the hottest place on Earth."],
  ["Chefchaouen", "MA", -5.26, 35.17, "culture", "The blue city of the Rif mountains."],
  ["Essaouira", "MA", -9.77, 31.51, "unesco", "Windsurf ramparts and gnawa music on the Atlantic."],
  ["Erg Chebbi", "MA", -4.00, 31.10, "park", "Camel treks into 150-m Saharan dunes."],
  ["Mount Toubkal", "MA", -7.92, 31.06, "park", "North Africa's highest summit, a two-day trek from Marrakesh."],
  ["Carthage", "TN", 10.32, 36.85, "unesco", "Rome's great rival, reduced to seaside ruins."],
  ["Sidi Bou Said", "TN", 10.35, 36.87, "culture", "Blue-and-white clifftop café village."],
  ["El Jem", "TN", 10.707, 35.296, "unesco", "A 35,000-seat colosseum in the Tunisian steppe."],
  ["Leptis Magna", "LY", 14.29, 32.64, "unesco", "The most spectacular Roman city in Africa."],
  ["Siwa Oasis", "EG", 25.52, 29.20, "culture", "Salt lakes and the oracle Alexander crossed a desert to consult."],
  ["White Desert", "EG", 27.67, 27.06, "park", "Wind-carved chalk mushrooms glowing at dusk."],
  ["Mount Sinai", "EG", 33.975, 28.54, "culture", "Sunrise from the mountain of the Ten Commandments."],
  ["Valley of the Kings", "EG", 32.601, 25.74, "unesco", "Tutankhamun's tomb among 60 royal burials."],
  ["Philae Temple", "EG", 32.884, 24.025, "unesco", "Isis's island temple, moved stone by stone from the flood."],
  ["Gorée Island", "SN", -17.40, 14.667, "unesco", "The house of slaves and its door of no return."],
  ["Timbuktu", "ML", -3.01, 16.77, "unesco", "The fabled city of 700,000 manuscripts."],
  ["Avenue of the Baobabs", "MG", 44.42, -20.25, "park", "800-year-old giants lining a red dirt road."],
  ["Tsingy de Bemaraha", "MG", 44.78, -18.66, "unesco", "A forest of razor-sharp limestone needles."],
  ["Vallée de Mai", "SC", 55.74, -4.33, "unesco", "The coco de mer's primeval palm valley."],
  ["Le Morne", "MU", 57.32, -20.45, "unesco", "Mauritius's maroon-refuge mountain over lagoon blues."],
  ["Piton de la Fournaise", "FR", 55.71, -21.24, "park", "Réunion's hyperactive shield volcano."],

  // ── North America ─────────────────────────────────────────────────────────
  ["Statue of Liberty", "US", -74.0445, 40.6892, "unesco", "Liberty Enlightening the World, gift of France, 1886."],
  ["Grand Canyon", "US", -112.1129, 36.1069, "park", "A mile-deep chasm carved over six million years."],
  ["Yellowstone", "US", -110.5885, 44.4280, "park", "The first national park: geysers, wolves, and bison."],
  ["Yosemite Valley", "US", -119.5383, 37.8651, "park", "Granite walls and waterfalls of the Sierra Nevada."],
  ["Zion National Park", "US", -113.0263, 37.2982, "park", "Slot canyons and sandstone cliffs in Utah."],
  ["Golden Gate Bridge", "US", -122.4783, 37.8199, "monument", "The Art-Deco span over San Francisco Bay."],
  ["Mount Rushmore", "US", -103.4591, 43.8791, "monument", "Four presidents carved into the Black Hills."],
  ["Mesa Verde", "US", -108.4618, 37.2309, "unesco", "Ancestral Puebloan cliff dwellings."],
  ["Independence Hall", "US", -75.1500, 39.9489, "unesco", "Where both the Declaration and Constitution were signed."],
  ["Banff National Park", "CA", -115.5708, 51.4968, "park", "Turquoise lakes beneath the Canadian Rockies."],
  ["Niagara Falls", "CA", -79.0742, 43.0799, "monument", "Three falls pouring a Great Lake over a cliff."],
  ["Old Québec", "CA", -71.2082, 46.8131, "unesco", "North America's only walled city north of Mexico."],
  ["Chichén Itzá", "MX", -88.5678, 20.6843, "unesco", "El Castillo and the great Maya observatory city."],
  ["Teotihuacan", "MX", -98.8438, 19.6925, "unesco", "Pyramids of the Sun and Moon on the Avenue of the Dead."],
  ["Tulum", "MX", -87.4287, 20.2114, "culture", "A Maya port fortress on Caribbean cliffs."],
  ["Antigua Guatemala", "GT", -90.7343, 14.5586, "unesco", "Baroque ruins beneath three volcanoes."],
  ["Tikal", "GT", -89.6237, 17.2220, "unesco", "Maya temples piercing the rainforest canopy."],
  ["Old Havana", "CU", -82.3496, 23.1367, "unesco", "Colonial plazas, classic cars and crumbling grandeur."],

  // ── South America ─────────────────────────────────────────────────────────
  ["Machu Picchu", "PE", -72.5450, -13.1631, "unesco", "The lost Inca citadel in the cloud forest."],
  ["Cusco Historic Centre", "PE", -71.9675, -13.5320, "unesco", "Inca walls under Spanish baroque."],
  ["Nazca Lines", "PE", -75.1300, -14.7390, "unesco", "Giant desert drawings best read from the sky."],
  ["Christ the Redeemer", "BR", -43.2105, -22.9519, "monument", "Rio's 38 m art-deco Christ atop Corcovado."],
  ["Iguazú Falls", "AR", -54.4367, -25.6953, "park", "275 falls on the Argentina–Brazil border."],
  ["Perito Moreno Glacier", "AR", -73.0500, -50.4967, "park", "A calving glacier wall you can watch collapse."],
  ["Torres del Paine", "CL", -73.0000, -50.9423, "park", "Granite towers over Patagonian steppe."],
  ["Easter Island / Rapa Nui", "CL", -109.3497, -27.1127, "unesco", "Nearly 900 moai on the world's loneliest island."],
  ["Galápagos Islands", "EC", -90.9656, -0.6293, "unesco", "Darwin's living laboratory of evolution."],
  ["Salar de Uyuni", "BO", -67.4891, -20.1338, "park", "The world's largest salt flat — a mirror after rain."],
  ["Cartagena Old Town", "CO", -75.5511, 10.4236, "unesco", "Walled Caribbean port of balconies and bougainvillea."],
  ["Angel Falls", "VE", -62.5356, 5.9701, "park", "979 m — the tallest waterfall on Earth."],

  // ── United States: every national park ────────────────────────────────────
  ["Acadia National Park", "US", -68.21, 44.35, "park", "Granite headlands where mountains meet the Atlantic."],
  ["National Park of American Samoa", "US", -170.68, -14.25, "park", "Paleotropical rainforest and coral reef in the South Pacific."],
  ["Arches National Park", "US", -109.57, 38.73, "park", "Over 2,000 natural sandstone arches, Delicate Arch among them."],
  ["Badlands National Park", "US", -102.50, 43.75, "park", "Striped buttes and fossil beds on the Dakota prairie."],
  ["Big Bend National Park", "US", -103.25, 29.25, "park", "The Rio Grande's great desert bend and darkest skies in Texas."],
  ["Biscayne National Park", "US", -80.21, 25.65, "park", "95% water — reefs, wrecks and mangrove keys."],
  ["Black Canyon of the Gunnison", "US", -107.72, 38.57, "park", "A gorge so steep parts see 33 minutes of sun a day."],
  ["Bryce Canyon National Park", "US", -112.18, 37.57, "park", "The world's densest collection of hoodoo spires."],
  ["Canyonlands National Park", "US", -109.88, 38.20, "park", "Island in the Sky mesas above the Colorado and Green rivers."],
  ["Capitol Reef National Park", "US", -111.17, 38.37, "park", "A 100-mile wrinkle in the earth called the Waterpocket Fold."],
  ["Carlsbad Caverns", "US", -104.44, 32.17, "park", "119 caves and a nightly exodus of half a million bats."],
  ["Channel Islands National Park", "US", -119.72, 34.01, "park", "California's Galápagos — five wild islands offshore."],
  ["Congaree National Park", "US", -80.78, 33.78, "park", "The largest old-growth bottomland forest left in the Southeast."],
  ["Crater Lake National Park", "US", -122.10, 42.94, "park", "America's deepest lake in a collapsed volcano, impossibly blue."],
  ["Cuyahoga Valley", "US", -81.55, 41.24, "park", "Waterfalls and towpath trails between Cleveland and Akron."],
  ["Death Valley National Park", "US", -117.08, 36.51, "park", "Hottest place on Earth, 282 ft below sea level at Badwater."],
  ["Denali National Park", "US", -151.19, 63.33, "park", "North America's highest peak rising 20,310 ft over tundra."],
  ["Dry Tortugas National Park", "US", -82.87, 24.63, "park", "A Civil War sea fortress 70 miles beyond Key West."],
  ["Everglades National Park", "US", -80.90, 25.32, "park", "The river of grass — alligators, manatees, and mangroves."],
  ["Gates of the Arctic", "US", -153.30, 67.78, "park", "No roads, no trails — pure Brooks Range wilderness."],
  ["Gateway Arch", "US", -90.19, 38.62, "monument", "Saarinen's 630-ft steel arch over the Mississippi."],
  ["Glacier National Park", "US", -113.79, 48.76, "park", "Going-to-the-Sun Road through the Crown of the Continent."],
  ["Glacier Bay National Park", "US", -136.80, 58.66, "park", "Tidewater glaciers calving into whale-filled fjords."],
  ["Grand Teton National Park", "US", -110.68, 43.73, "park", "The Tetons' sawtooth skyline with no foothills to soften it."],
  ["Great Basin National Park", "US", -114.26, 38.98, "park", "5,000-year-old bristlecone pines and Lehman Caves."],
  ["Great Sand Dunes", "US", -105.51, 37.73, "park", "North America's tallest dunes against the Sangre de Cristos."],
  ["Great Smoky Mountains", "US", -83.51, 35.61, "park", "America's most-visited park — blue ridges and synchronous fireflies."],
  ["Guadalupe Mountains", "US", -104.87, 31.92, "park", "Texas's highest peak atop an ancient fossil reef."],
  ["Haleakalā National Park", "US", -156.17, 20.72, "park", "Sunrise above the clouds from a 10,000-ft volcano crater."],
  ["Hawaiʻi Volcanoes", "US", -155.29, 19.42, "park", "Kīlauea's live lava meets the sea."],
  ["Hot Springs National Park", "US", -93.05, 34.51, "park", "Bathhouse Row and 143°F thermal springs."],
  ["Indiana Dunes", "US", -87.05, 41.65, "park", "15 miles of Lake Michigan shore and singing sands."],
  ["Isle Royale National Park", "US", -88.55, 48.00, "park", "A wolf-and-moose island wilderness in Lake Superior."],
  ["Joshua Tree National Park", "US", -115.90, 33.87, "park", "Dr. Seuss trees and granite boulders where two deserts meet."],
  ["Katmai National Park", "US", -155.01, 58.60, "park", "Brown bears fishing the falls at Brooks Camp."],
  ["Kenai Fjords National Park", "US", -149.65, 59.92, "park", "The Harding Icefield spilling glaciers into the Gulf of Alaska."],
  ["Kings Canyon National Park", "US", -118.55, 36.89, "park", "A canyon deeper than the Grand, and giant sequoia groves."],
  ["Kobuk Valley National Park", "US", -159.28, 67.35, "park", "Arctic sand dunes and half a million migrating caribou."],
  ["Lake Clark National Park", "US", -153.42, 60.97, "park", "Turquoise lakes, smoking volcanoes, fly-in-only solitude."],
  ["Lassen Volcanic National Park", "US", -121.41, 40.50, "park", "Boiling mudpots beneath a dormant plug-dome volcano."],
  ["Mammoth Cave National Park", "US", -86.10, 37.19, "park", "The longest cave system on Earth — 400+ mapped miles."],
  ["Mount Rainier National Park", "US", -121.73, 46.85, "park", "An icebound 14,410-ft volcano ringed by wildflower meadows."],
  ["New River Gorge", "US", -81.07, 37.93, "park", "One of the oldest rivers on Earth, under a famous steel arch."],
  ["North Cascades National Park", "US", -121.20, 48.70, "park", "The American Alps — 300+ glaciers, jagged and empty."],
  ["Olympic National Park", "US", -123.60, 47.80, "park", "Rainforest, alpine ridges and wild coast in one park."],
  ["Petrified Forest National Park", "US", -109.78, 35.07, "park", "225-million-year-old crystal logs in the Painted Desert."],
  ["Pinnacles National Park", "US", -121.16, 36.48, "park", "Volcanic spires, talus caves and soaring condors."],
  ["Redwood National Park", "US", -124.00, 41.30, "park", "The tallest trees on Earth, shrouded in Pacific fog."],
  ["Rocky Mountain National Park", "US", -105.68, 40.35, "park", "Trail Ridge Road tops 12,000 ft among elk and alpine tundra."],
  ["Saguaro National Park", "US", -110.50, 32.25, "park", "Forests of 50-ft cacti flanking Tucson."],
  ["Sequoia National Park", "US", -118.57, 36.49, "park", "General Sherman — the largest living tree on Earth."],
  ["Shenandoah National Park", "US", -78.35, 38.53, "park", "Skyline Drive along the Blue Ridge, 75 overlooks."],
  ["Theodore Roosevelt National Park", "US", -103.43, 46.97, "park", "Badlands and wild horses that shaped a president."],
  ["Virgin Islands National Park", "US", -64.75, 18.34, "park", "Trunk Bay's white sand and underwater snorkel trail."],
  ["Voyageurs National Park", "US", -92.88, 48.50, "park", "A maze of border lakes best traveled by boat."],
  ["White Sands National Park", "US", -106.33, 32.78, "park", "275 square miles of gypsum dunes, white as snow."],
  ["Wind Cave National Park", "US", -103.48, 43.57, "park", "Rare boxwork formations beneath bison prairie."],
  ["Wrangell–St. Elias", "US", -142.00, 61.50, "park", "America's largest park — six Yellowstones of peaks and ice."],
  // US monuments & culture
  ["Lincoln Memorial", "US", -77.050, 38.889, "monument", "Lincoln enthroned above the reflecting pool."],
  ["Washington Monument", "US", -77.035, 38.889, "monument", "The 555-ft marble obelisk anchoring the National Mall."],
  ["Empire State Building", "US", -73.985, 40.748, "monument", "New York's Art-Deco definition of a skyscraper."],
  ["Brooklyn Bridge", "US", -73.997, 40.706, "monument", "The 1883 stone-and-steel span that made Brooklyn part of NYC."],
  ["Alcatraz Island", "US", -122.423, 37.827, "culture", "The Rock — America's most infamous former prison."],
  ["Hollywood Sign", "US", -118.322, 34.134, "culture", "Nine white letters watching over the film capital."],
  ["Space Needle", "US", -122.349, 47.620, "monument", "Seattle's 1962 World's Fair flying saucer on a stick."],
  ["Hoover Dam", "US", -114.738, 36.016, "monument", "The concrete colossus that tamed the Colorado."],
  ["Monument Valley", "US", -110.11, 36.98, "park", "The sandstone buttes of every western ever filmed."],
  ["Antelope Canyon", "US", -111.37, 36.86, "park", "Light beams in a sculpted sandstone slot on Navajo land."],
  ["Devils Tower", "US", -104.71, 44.59, "monument", "An 867-ft volcanic column sacred to Plains tribes."],
  ["Niagara Falls (US)", "US", -79.06, 43.09, "park", "The American side's thundering curtain of water."],
  ["French Quarter", "US", -90.065, 29.958, "culture", "New Orleans' Creole heart of jazz, balconies and beignets."],
  ["Freedom Trail", "US", -71.060, 42.360, "culture", "2.5 miles of Boston's revolutionary history."],
  ["Taos Pueblo", "US", -105.549, 36.439, "unesco", "Multi-storied adobe lived in for over 1,000 years."],
  ["Cahokia Mounds", "US", -90.062, 38.655, "unesco", "The greatest pre-Columbian city north of Mexico."],
  ["Golden Gate Park", "US", -122.48, 37.77, "culture", "San Francisco's mile-wide green lung of gardens and museums."],
  ["Las Vegas Strip", "US", -115.172, 36.114, "culture", "Four neon miles of casinos and spectacle."],
  ["Times Square", "US", -73.9855, 40.758, "culture", "The crossroads of the world, lit 24/7."],
  // ── Canada ────────────────────────────────────────────────────────────────
  ["Jasper National Park", "CA", -118.08, 52.87, "park", "The Rockies' biggest park — glaciers, elk and dark skies."],
  ["Yoho National Park", "CA", -116.50, 51.40, "park", "Takakkaw Falls and the Burgess Shale fossil beds."],
  ["Waterton Lakes", "CA", -113.90, 49.05, "park", "Where the prairies crash straight into the mountains."],
  ["Pacific Rim", "CA", -125.70, 49.00, "park", "Storm-watching, surf and old-growth on Vancouver Island."],
  ["Gros Morne", "CA", -57.75, 49.60, "unesco", "The Earth's mantle exposed in Newfoundland's Tablelands."],
  ["Nahanni", "CA", -123.50, 61.55, "unesco", "Virginia Falls — twice Niagara's height, deep in the Northwest."],
  ["L'Anse aux Meadows", "CA", -55.53, 51.60, "unesco", "The only confirmed Viking site in North America."],
  ["Bay of Fundy", "CA", -64.75, 45.60, "park", "The world's highest tides, 50 vertical feet twice a day."],
  ["CN Tower", "CA", -79.387, 43.643, "monument", "Toronto's 553-m spire with a glass floor to test your nerve."],
  ["Parliament Hill", "CA", -75.700, 45.425, "monument", "Gothic-revival seat of Canadian government above the Ottawa River."],
  ["Whistler Blackcomb", "CA", -122.95, 50.115, "park", "North America's largest ski resort, twin peaks linked by gondola."],

  // ── Latin America & Caribbean (more) ──────────────────────────────────────
  ["Palenque", "MX", -92.05, 17.48, "unesco", "Maya temples half-swallowed by Chiapas jungle."],
  ["Uxmal", "MX", -89.77, 20.36, "unesco", "The Pyramid of the Magician's rounded Puuc grace."],
  ["Monte Albán", "MX", -96.77, 17.04, "unesco", "A mountaintop leveled into a Zapotec capital."],
  ["Guanajuato", "MX", -101.25, 21.02, "unesco", "A silver city of tunnels and candy-colored houses."],
  ["Mexico City Centro Histórico", "MX", -99.133, 19.433, "unesco", "The Zócalo, built on the ruins of Tenochtitlan."],
  ["Copper Canyon", "MX", -107.75, 27.50, "park", "A canyon system deeper and larger than the Grand."],
  ["Copán", "HN", -89.14, 14.84, "unesco", "The Maya world's finest carved stelae."],
  ["Tikal", "GT", -89.62, 17.22, "unesco", "Temple IV rising above the Petén canopy at dawn."],
  ["Arenal Volcano", "CR", -84.70, 10.46, "park", "Costa Rica's perfect cone above hot springs."],
  ["Monteverde Cloud Forest", "CR", -84.79, 10.30, "park", "Hanging bridges through the cloud line, quetzals included."],
  ["Manuel Antonio", "CR", -84.15, 9.39, "park", "Sloths and capuchins above white-sand coves."],
  ["Corcovado", "CR", -83.59, 8.54, "park", "The most biologically intense place on Earth, per National Geographic."],
  ["Panama Canal", "PA", -79.92, 9.08, "monument", "The 50-mile shortcut between two oceans."],
  ["Great Blue Hole", "BZ", -87.53, 17.32, "park", "A 400-ft-deep sinkhole ringed by reef."],
  ["Granada", "NI", -85.95, 11.93, "culture", "The oldest colonial city in the Americas, on Lake Nicaragua."],
  ["El Yunque", "PR", -65.80, 18.30, "park", "The US's only tropical rainforest, coquí frogs singing."],
  ["Pitons", "LC", -61.07, 13.80, "unesco", "St. Lucia's twin volcanic spires from the sea."],
  ["Trinidad", "CU", -79.98, 21.80, "unesco", "Cobblestones and pastel palaces frozen since the sugar boom."],
  ["Viñales Valley", "CU", -83.70, 22.62, "unesco", "Tobacco farms beneath dome-like mogote hills."],
  ["Rainbow Mountain", "PE", -71.35, -13.87, "park", "Vinicunca's striped mineral slopes at 5,000 m."],
  ["Ollantaytambo", "PE", -72.26, -13.26, "unesco", "A living Inca town and fortress in the Sacred Valley."],
  ["Colca Canyon", "PE", -71.90, -15.60, "park", "Condors riding thermals in a canyon twice the Grand's depth."],
  ["Lake Titicaca", "PE", -69.50, -15.80, "park", "The highest navigable lake and its floating reed islands."],
  ["Huacachina", "PE", -75.76, -14.09, "park", "A palm-ringed oasis amid giant dunes."],
  ["Ciudad Perdida", "CO", -73.93, 11.04, "unesco", "The Lost City — a four-day jungle trek older than Machu Picchu."],
  ["Tayrona", "CO", -74.00, 11.30, "park", "Caribbean coves beneath the Sierra Nevada."],
  ["Cocora Valley", "CO", -75.49, 4.64, "park", "The world's tallest palms in Colombia's coffee hills."],
  ["Cotopaxi", "EC", -78.44, -0.68, "park", "One of the world's highest active volcanoes, perfectly conical."],
  ["Quito Old Town", "EC", -78.51, -0.22, "unesco", "The best-preserved colonial center in the Americas."],
  ["Valle de la Luna", "CL", -68.30, -22.92, "park", "Atacama moonscapes at the driest place on Earth."],
  ["Valparaíso", "CL", -71.62, -33.05, "unesco", "Funiculars and murals stacked on 42 hills."],
  ["Aconcagua", "AR", -70.01, -32.65, "park", "The highest peak outside Asia at 6,961 m."],
  ["Nahuel Huapi / Bariloche", "AR", -71.50, -41.10, "park", "Alpine lakes and chocolate shops in Argentine Patagonia."],
  ["Fitz Roy / El Chaltén", "AR", -72.90, -49.27, "park", "Patagonia's granite spear and trekking capital."],
  ["Tierra del Fuego", "AR", -68.50, -54.85, "park", "The end of the world, where the Andes sink into the sea."],
  ["Fernando de Noronha", "BR", -32.42, -3.85, "unesco", "Brazil's volcanic archipelago of spinner dolphins."],
  ["Lençóis Maranhenses", "BR", -43.12, -2.53, "park", "White dunes holding thousands of turquoise rain lagoons."],
  ["Pantanal", "BR", -56.60, -17.70, "unesco", "The world's largest wetland — best jaguar watching anywhere."],
  ["Sugarloaf Mountain", "BR", -43.157, -22.949, "monument", "The cable-car granite dome over Guanabara Bay."],
  ["Ouro Preto", "BR", -43.50, -20.38, "unesco", "Baroque gold-rush churches in the Minas hills."],
  ["Pelourinho, Salvador", "BR", -38.51, -12.97, "unesco", "Afro-Brazilian heart of drums and pastel facades."],
  ["Meeting of the Waters", "BR", -60.02, -3.13, "park", "The Rio Negro and Solimões run side by side, unmixed."],
  ["Colonia del Sacramento", "UY", -57.85, -34.47, "unesco", "Portuguese cobbles on the Río de la Plata."],
  ["Salto Ángel", "VE", -62.5356, 5.9701, "park", "Angel Falls' mile-high plunge off Auyán-tepui."],

  // ── Oceania ───────────────────────────────────────────────────────────────
  ["Sydney Opera House", "AU", 151.2153, -33.8568, "unesco", "The sail-roofed icon of Sydney Harbour."],
  ["Uluru", "AU", 131.0369, -25.3444, "unesco", "The sacred red monolith of the Anangu."],
  ["Great Barrier Reef", "AU", 146.8169, -18.2871, "unesco", "2,300 km of living coral — visible from space."],
  ["Twelve Apostles", "AU", 143.1044, -38.6645, "park", "Limestone stacks along the Great Ocean Road."],
  ["Milford Sound", "NZ", 167.9256, -44.6717, "park", "Fiordland's rain-soaked cathedral of cliffs."],
  ["Tongariro", "NZ", 175.6321, -39.2726, "unesco", "Volcanic crossing over emerald crater lakes."],
  ["Nan Madol", "FM", 158.3352, 6.8441, "unesco", "A ruined basalt city built on a coral lagoon."],
  ["Sydney Harbour Bridge", "AU", 151.2108, -33.8523, "monument", "Climb the coathanger for the best view of the Opera House."],
  ["Bondi Beach", "AU", 151.274, -33.891, "culture", "Australia's most famous surf and the Icebergs pool."],
  ["Blue Mountains", "AU", 150.31, -33.72, "unesco", "Eucalyptus haze over the Three Sisters."],
  ["Kakadu", "AU", 132.90, -12.85, "unesco", "65,000 years of rock art amid crocodile wetlands."],
  ["Daintree Rainforest", "AU", 145.42, -16.17, "unesco", "The oldest rainforest on Earth meets the reef."],
  ["K'gari (Fraser Island)", "AU", 153.13, -25.24, "unesco", "The world's largest sand island, rainforest growing on dunes."],
  ["Whitehaven Beach", "AU", 149.04, -20.28, "park", "Pure silica sand swirling into the Coral Sea."],
  ["Ningaloo Reef", "AU", 113.80, -22.70, "unesco", "Swim with whale sharks right off the beach."],
  ["Purnululu", "AU", 128.40, -17.50, "unesco", "The Bungle Bungles' striped beehive domes."],
  ["Cradle Mountain", "AU", 145.95, -41.68, "park", "Tasmania's jagged icon above Dove Lake."],
  ["Wineglass Bay", "AU", 148.30, -42.15, "park", "A perfect arc of white sand in Freycinet."],
  ["Kangaroo Island", "AU", 137.20, -35.80, "park", "Sea lions, koalas and Remarkable Rocks."],
  ["Rottnest Island", "AU", 115.52, -32.00, "park", "Home of the quokka selfie."],
  ["Hobbiton", "NZ", 175.68, -37.87, "culture", "The Shire's 44 hobbit holes, kept movie-perfect."],
  ["Rotorua", "NZ", 176.25, -38.14, "park", "Geysers, mud pools and living Māori culture."],
  ["Aoraki / Mount Cook", "NZ", 170.14, -43.60, "park", "New Zealand's highest peak over the Hooker Valley."],
  ["Franz Josef Glacier", "NZ", 170.18, -43.47, "park", "A glacier descending nearly to rainforest."],
  ["Queenstown", "NZ", 168.66, -45.03, "park", "The adventure capital beneath the Remarkables."],
  ["Waitomo Caves", "NZ", 175.11, -38.26, "park", "A starry ceiling of glowworms, by boat."],
  ["Bay of Islands", "NZ", 174.09, -35.22, "park", "144 subtropical islands and the Treaty grounds."],
  ["Bora Bora", "PF", -151.74, -16.50, "park", "The lagoon that defines paradise."],
  ["Moorea", "PF", -149.83, -17.53, "park", "Shark-and-ray snorkeling under serrated peaks."],
  ["Mount Yasur", "VU", 169.44, -19.53, "park", "Stand at the rim of a continuously erupting volcano."],
  ["Rock Islands", "PW", 134.37, 7.27, "unesco", "Palau's mushroom isles and Jellyfish Lake."],
  ["To Sua Ocean Trench", "WS", -171.72, -14.05, "park", "Samoa's ladder-down swimming hole."],
];

export const LANDMARKS: Landmark[] = rows.map(([name, countryCode, lng, lat, category, blurb], i) => ({
  id: `lm-${i + 1}`,
  name,
  countryCode,
  lng,
  lat,
  category,
  blurb,
}));
