import type { CountryRules } from "../rules";

import r_ae from "./ae.json";
import r_al from "./al.json";
import r_am from "./am.json";
import r_ar from "./ar.json";
import r_at from "./at.json";
import r_au from "./au.json";
import r_ba from "./ba.json";
import r_be from "./be.json";
import r_bg from "./bg.json";
import r_br from "./br.json";
import r_bt from "./bt.json";
import r_bw from "./bw.json";
import r_ca from "./ca.json";
import r_ch from "./ch.json";
import r_cl from "./cl.json";
import r_cn from "./cn.json";
import r_co from "./co.json";
import r_cr from "./cr.json";
import r_cu from "./cu.json";
import r_cy from "./cy.json";
import r_cz from "./cz.json";
import r_de from "./de.json";
import r_dk from "./dk.json";
import r_do from "./do.json";
import r_ec from "./ec.json";
import r_ee from "./ee.json";
import r_eg from "./eg.json";
import r_es from "./es.json";
import r_et from "./et.json";
import r_fi from "./fi.json";
import r_fj from "./fj.json";
import r_fr from "./fr.json";
import r_gb from "./gb.json";
import r_ge from "./ge.json";
import r_gh from "./gh.json";
import r_gr from "./gr.json";
import r_hk from "./hk.json";
import r_hr from "./hr.json";
import r_hu from "./hu.json";
import r_id from "./id.json";
import r_ie from "./ie.json";
import r_il from "./il.json";
import r_in from "./in.json";
import r_is from "./is.json";
import r_it from "./it.json";
import r_jo from "./jo.json";
import r_jp from "./jp.json";
import r_ke from "./ke.json";
import r_kg from "./kg.json";
import r_kh from "./kh.json";
import r_kr from "./kr.json";
import r_kz from "./kz.json";
import r_la from "./la.json";
import r_li from "./li.json";
import r_lk from "./lk.json";
import r_lt from "./lt.json";
import r_lu from "./lu.json";
import r_lv from "./lv.json";
import r_ma from "./ma.json";
import r_me from "./me.json";
import r_mk from "./mk.json";
import r_mn from "./mn.json";
import r_mt from "./mt.json";
import r_mu from "./mu.json";
import r_mv from "./mv.json";
import r_mx from "./mx.json";
import r_my from "./my.json";
import r_na from "./na.json";
import r_ng from "./ng.json";
import r_nl from "./nl.json";
import r_no from "./no.json";
import r_np from "./np.json";
import r_nz from "./nz.json";
import r_om from "./om.json";
import r_pa from "./pa.json";
import r_pe from "./pe.json";
import r_pf from "./pf.json";
import r_ph from "./ph.json";
import r_pl from "./pl.json";
import r_pt from "./pt.json";
import r_qa from "./qa.json";
import r_ro from "./ro.json";
import r_rs from "./rs.json";
import r_rw from "./rw.json";
import r_sa from "./sa.json";
import r_sc from "./sc.json";
import r_se from "./se.json";
import r_sg from "./sg.json";
import r_si from "./si.json";
import r_sk from "./sk.json";
import r_th from "./th.json";
import r_tn from "./tn.json";
import r_tr from "./tr.json";
import r_tw from "./tw.json";
import r_tz from "./tz.json";
import r_ua from "./ua.json";
import r_ug from "./ug.json";
import r_us from "./us.json";
import r_uy from "./uy.json";
import r_uz from "./uz.json";
import r_vn from "./vn.json";
import r_za from "./za.json";

// The registry of published country files, in three labelled tiers:
// "verified" (a pilot read the sources and has flown there), "desk-review"
// (official sources read at a desk), and "unverified" (written from general
// knowledge; the authority page is listed to check). Generated by
// scripts/fieldbrief/unverified-countries.py for the third tier; the other
// two are edited by hand. tests/fieldbrief-rules.test.ts keeps the folder and
// this list in agreement.
export const RULE_FILES: Record<string, CountryRules> = {
  AE: r_ae as unknown as CountryRules,
  AL: r_al as unknown as CountryRules,
  AM: r_am as unknown as CountryRules,
  AR: r_ar as unknown as CountryRules,
  AT: r_at as unknown as CountryRules,
  AU: r_au as unknown as CountryRules,
  BA: r_ba as unknown as CountryRules,
  BE: r_be as unknown as CountryRules,
  BG: r_bg as unknown as CountryRules,
  BR: r_br as unknown as CountryRules,
  BT: r_bt as unknown as CountryRules,
  BW: r_bw as unknown as CountryRules,
  CA: r_ca as unknown as CountryRules,
  CH: r_ch as unknown as CountryRules,
  CL: r_cl as unknown as CountryRules,
  CN: r_cn as unknown as CountryRules,
  CO: r_co as unknown as CountryRules,
  CR: r_cr as unknown as CountryRules,
  CU: r_cu as unknown as CountryRules,
  CY: r_cy as unknown as CountryRules,
  CZ: r_cz as unknown as CountryRules,
  DE: r_de as unknown as CountryRules,
  DK: r_dk as unknown as CountryRules,
  DO: r_do as unknown as CountryRules,
  EC: r_ec as unknown as CountryRules,
  EE: r_ee as unknown as CountryRules,
  EG: r_eg as unknown as CountryRules,
  ES: r_es as unknown as CountryRules,
  ET: r_et as unknown as CountryRules,
  FI: r_fi as unknown as CountryRules,
  FJ: r_fj as unknown as CountryRules,
  FR: r_fr as unknown as CountryRules,
  GB: r_gb as unknown as CountryRules,
  GE: r_ge as unknown as CountryRules,
  GH: r_gh as unknown as CountryRules,
  GR: r_gr as unknown as CountryRules,
  HK: r_hk as unknown as CountryRules,
  HR: r_hr as unknown as CountryRules,
  HU: r_hu as unknown as CountryRules,
  ID: r_id as unknown as CountryRules,
  IE: r_ie as unknown as CountryRules,
  IL: r_il as unknown as CountryRules,
  IN: r_in as unknown as CountryRules,
  IS: r_is as unknown as CountryRules,
  IT: r_it as unknown as CountryRules,
  JO: r_jo as unknown as CountryRules,
  JP: r_jp as unknown as CountryRules,
  KE: r_ke as unknown as CountryRules,
  KG: r_kg as unknown as CountryRules,
  KH: r_kh as unknown as CountryRules,
  KR: r_kr as unknown as CountryRules,
  KZ: r_kz as unknown as CountryRules,
  LA: r_la as unknown as CountryRules,
  LI: r_li as unknown as CountryRules,
  LK: r_lk as unknown as CountryRules,
  LT: r_lt as unknown as CountryRules,
  LU: r_lu as unknown as CountryRules,
  LV: r_lv as unknown as CountryRules,
  MA: r_ma as unknown as CountryRules,
  ME: r_me as unknown as CountryRules,
  MK: r_mk as unknown as CountryRules,
  MN: r_mn as unknown as CountryRules,
  MT: r_mt as unknown as CountryRules,
  MU: r_mu as unknown as CountryRules,
  MV: r_mv as unknown as CountryRules,
  MX: r_mx as unknown as CountryRules,
  MY: r_my as unknown as CountryRules,
  NA: r_na as unknown as CountryRules,
  NG: r_ng as unknown as CountryRules,
  NL: r_nl as unknown as CountryRules,
  NO: r_no as unknown as CountryRules,
  NP: r_np as unknown as CountryRules,
  NZ: r_nz as unknown as CountryRules,
  OM: r_om as unknown as CountryRules,
  PA: r_pa as unknown as CountryRules,
  PE: r_pe as unknown as CountryRules,
  PF: r_pf as unknown as CountryRules,
  PH: r_ph as unknown as CountryRules,
  PL: r_pl as unknown as CountryRules,
  PT: r_pt as unknown as CountryRules,
  QA: r_qa as unknown as CountryRules,
  RO: r_ro as unknown as CountryRules,
  RS: r_rs as unknown as CountryRules,
  RW: r_rw as unknown as CountryRules,
  SA: r_sa as unknown as CountryRules,
  SC: r_sc as unknown as CountryRules,
  SE: r_se as unknown as CountryRules,
  SG: r_sg as unknown as CountryRules,
  SI: r_si as unknown as CountryRules,
  SK: r_sk as unknown as CountryRules,
  TH: r_th as unknown as CountryRules,
  TN: r_tn as unknown as CountryRules,
  TR: r_tr as unknown as CountryRules,
  TW: r_tw as unknown as CountryRules,
  TZ: r_tz as unknown as CountryRules,
  UA: r_ua as unknown as CountryRules,
  UG: r_ug as unknown as CountryRules,
  US: r_us as unknown as CountryRules,
  UY: r_uy as unknown as CountryRules,
  UZ: r_uz as unknown as CountryRules,
  VN: r_vn as unknown as CountryRules,
  ZA: r_za as unknown as CountryRules,
};
